pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        id 'org.springframework.boot' version '4.0.2'
        id 'io.spring.dependency-management' version '1.1.7'
        id 'com.google.cloud.tools.jib' version '3.5.3'
    }
}

rootProject.name = 'ecogod'

include 'ecogod-api', 'ecogod-domain', 'ecogod-infra', 'ecogod-common', 'ecogod-auth', 'ecogod-external'
