plugins {
    id 'java-library'
}

dependencies {
    implementation project(':ecogod-domain')
    implementation project(':ecogod-common')

    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'software.amazon.awssdk:s3:2.32.18'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
